"""Validate the AI Development OS repository structure."""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

REQUIRED = [
    "README.md",
    "AGENTS.md",
    "CONTRIBUTING.md",
    "CONTRIBUTOR_TERMS.md",
    "DCO.txt",
    "GOVERNANCE.md",
    "LICENSE",
    "NOTICE.md",
    "DISCLAIMER.md",
    "ROADMAP.md",
    "SECURITY.md",
    "TRADEMARKS.md",
    "docs/LICENSING.md",
    "docs/COMMERCIAL_AND_ASSOCIATION.md",
    "docs/INSTRUCTION_NORMALIZATION.md",
    "docs/COMPLEXITY_ROUTER.md",
    "docs/AGENTIC_COMPANY_MODEL.md",
    "docs/DELIVERY_ESTIMATION.md",
    "docs/AI_NATIVE_DELIVERY.md",
    "docs/STARTUP_LIFECYCLE_DEVELOPMENT.md",
    "docs/PRODUCT_AUTOMATION_GUIDE.md",
    "docs/AGENTIC_WORKFLOW_INTEGRATION.md",
    "docs/STARTUP_CONTINUATION_RULE.md",
    "docs/VC_PITCH_READINESS.md",
    "docs/BOARD_GO_LIVE_READINESS.md",
    "docs/EXTERNAL_AGENT_HARNESS_INTEGRATION.md",
    "docs/SYSTEM_REVIEW_GRAPH.md",
    "docs/STATE_RECONSTRUCTION.md",
    "docs/AI_LIFECYCLE.md",
    "docs/BIDIRECTIONAL_PRODUCT_LOOP.md",
    "docs/PROMPT_TO_PRODUCT.md",
    "docs/COMPLEX_PRODUCT_PLAYBOOK.md",
    "docs/TOOL_BREEDING_GROUND.md",
    "docs/STRATEGY_RESEARCH_PLAYBOOK.md",
    "docs/TOOLCHAIN.md",
    "docs/OPEN_SOURCE_RESOURCES.md",
    "docs/RESEARCH_INTAKE.md",
    "docs/CODEX_USAGE.md",
    "docs/NO_SCAFFOLD_DELIVERY_POLICY.md",
    "manifests/tool_registry.yaml",
    "manifests/agent_lanes.yaml",
    "manifests/agentic_workflow_manifest.json",
    "manifests/agentic_execution_manifest.json",
    "manifests/internal_repo_registry.json",
    "manifests/research_data_router.json",
    "manifests/development_strategy_router.json",
    ".github/pull_request_template.md",
    ".github/ISSUE_TEMPLATE/bug_report.md",
    ".github/ISSUE_TEMPLATE/process_gap.md",
    "examples/README.md",
    "examples/calculator_app_prompt.txt",
    "examples/calculator_app_expected/COMPLEXITY_CLASSIFICATION.md",
    "examples/hardware_os_startup_prompt.txt",
    "examples/hardware_os_startup_expected/COMPLEXITY_CLASSIFICATION.md",
    "examples/hardware_os_startup_expected/INSTRUCTION_CONTRACT.md",
    "examples/hardware_os_startup_expected/ARCHITECTURE_OVERVIEW.md",
    "examples/hardware_os_startup_expected/DELIVERY_ESTIMATE.md",
    "examples/hardware_os_startup_expected/TOOL_DECISION_RECORD.md",
    "product_projects/README.md",
    "product_projects/importer-source-readiness-copilot/README.md",
    "product_projects/importer-source-readiness-copilot/AGENTS.md",
    "product_projects/importer-source-readiness-copilot/PRODUCT_DOCTRINE.md",
    "product_projects/importer-source-readiness-copilot/CUSTOMER_SOURCE_PACKET_SPEC.md",
    "product_projects/importer-source-readiness-copilot/SOURCE_OF_TRUTH.md",
    "product_projects/importer-source-readiness-copilot/RUN_RESULTS.md",
    "product_projects/importer-source-readiness-copilot/EXTERNAL_REVIEW_SUMMARY.md",
    "product_projects/importer-source-readiness-copilot/REDACTION_REPORT.md",
    "product_projects/importer-source-readiness-copilot/REVIEW_USE_TERMS.md",
    "product_projects/importer-source-readiness-copilot/OFFLINE_REPRODUCTION.md",
    "product_projects/importer-source-readiness-copilot/PACKAGE_AUDIT.md",
    "product_projects/importer-source-readiness-copilot/docs/PRODUCT_AUTOMATION_RUNBOOK.md",
    "product_projects/importer-source-readiness-copilot/docs/PRODUCT_STATUS.md",
    "product_projects/importer-source-readiness-copilot/docs/REQUIREMENTS_ANALYSIS.md",
    "product_projects/importer-source-readiness-copilot/docs/PUBLIC_TRADE_READINESS.md",
    "product_projects/importer-source-readiness-copilot/docs/ALL_STAGES_COMPLETION.md",
    "product_projects/importer-source-readiness-copilot/docs/AI_DATA_POLICY.md",
    "product_projects/importer-source-readiness-copilot/docs/DOCUMENT_PROCESSING.md",
    "product_projects/importer-source-readiness-copilot/docs/OPPORTUNITY_SCANNER.md",
    "product_projects/importer-source-readiness-copilot/docs/POLICY_MONITORING.md",
    "product_projects/importer-source-readiness-copilot/docs/AGENT_API.md",
    "product_projects/importer-source-readiness-copilot/docs/STARTUP_LIFECYCLE.md",
    "product_projects/importer-source-readiness-copilot/docs/OPERATOR_GUIDE.md",
    "product_projects/importer-source-readiness-copilot/docs/UI_UX_COMPONENT_SYSTEM.md",
    "product_projects/importer-source-readiness-copilot/docs/EXTERNAL_REVIEW_PROCESS.md",
    "product_projects/importer-source-readiness-copilot/docs/EXTERNAL_VALIDATION_REQUIREMENTS.md",
    "product_projects/importer-source-readiness-copilot/docs/EXTERNAL_VALIDATION_REVIEWER_BRIEF.md",
    "product_projects/importer-source-readiness-copilot/docs/GO_LIVE_INPUT_REQUESTS.md",
    "product_projects/importer-source-readiness-copilot/docs/BUSINESS_CORE_LOGIC_CURRENT_STATE.md",
    "product_projects/importer-source-readiness-copilot/docs/FUNCTIONAL_REQUIREMENTS_CURRENT_STATE.md",
    "product_projects/importer-source-readiness-copilot/docs/NON_FUNCTIONAL_REQUIREMENTS_CURRENT_STATE.md",
    "product_projects/importer-source-readiness-copilot/data/sample_source_cards.json",
    "product_projects/importer-source-readiness-copilot/data/country_requirements_matrix.json",
    "product_projects/importer-source-readiness-copilot/data/evidence_packets.json",
    "product_projects/importer-source-readiness-copilot/data/official_source_registry.json",
    "product_projects/importer-source-readiness-copilot/data/investor_evidence.json",
    "product_projects/importer-source-readiness-copilot/data/canada_tool_registry.json",
    "product_projects/importer-source-readiness-copilot/data/expert_review_simulations.json",
    "product_projects/importer-source-readiness-copilot/data/launch_controls.json",
    "product_projects/importer-source-readiness-copilot/data/customer_source_packets.json",
    "product_projects/importer-source-readiness-copilot/data/evidence_ledger.json",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/readiness.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/external_gates.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/continuation.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/investor_readiness.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/board_readiness.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/operator_app.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/operator_workflow.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/operator_report.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/operator_screenshots.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/source_packet_workflow.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/customer_store.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/product_runtime.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/document_processing.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/policy_intelligence.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/completion_platform.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/business_logic.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/product_operations.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/ai_review_validation.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/external_review.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/final_go_live.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/external_validation_research.py",
    "product_projects/importer-source-readiness-copilot/scripts/run_readiness.py",
    "product_projects/importer-source-readiness-copilot/scripts/run_external_gates.py",
    "product_projects/importer-source-readiness-copilot/scripts/export_operator_dashboard.py",
    "product_projects/importer-source-readiness-copilot/scripts/plan_continuation.py",
    "product_projects/importer-source-readiness-copilot/scripts/build_vc_pitch_packet.py",
    "product_projects/importer-source-readiness-copilot/scripts/build_board_go_live_packet.py",
    "product_projects/importer-source-readiness-copilot/scripts/serve_operator_app.py",
    "product_projects/importer-source-readiness-copilot/scripts/run_operator_workflow.py",
    "product_projects/importer-source-readiness-copilot/scripts/run_customer_workflow.py",
    "product_projects/importer-source-readiness-copilot/scripts/run_policy_intelligence.py",
    "product_projects/importer-source-readiness-copilot/scripts/run_completion_platform.py",
    "product_projects/importer-source-readiness-copilot/scripts/run_product_operations.py",
    "product_projects/importer-source-readiness-copilot/scripts/build_external_review_packet.py",
    "product_projects/importer-source-readiness-copilot/scripts/audit_external_package.py",
    "product_projects/importer-source-readiness-copilot/scripts/run_final_go_live_review.py",
    "product_projects/importer-source-readiness-copilot/scripts/run_external_validation_requirements.py",
    "product_projects/importer-source-readiness-copilot/scripts/package_external_review.py",
    "product_projects/importer-source-readiness-copilot/scripts/check_product.py",
    "product_projects/importer-source-readiness-copilot/tests/test_readiness.py",
    "product_projects/importer-source-readiness-copilot/tests/test_external_gates.py",
    "product_projects/importer-source-readiness-copilot/tests/test_continuation.py",
    "product_projects/importer-source-readiness-copilot/tests/test_investor_readiness.py",
    "product_projects/importer-source-readiness-copilot/tests/test_board_go_live.py",
    "product_projects/importer-source-readiness-copilot/tests/test_operator_app.py",
    "product_projects/importer-source-readiness-copilot/tests/test_operator_workflow.py",
    "product_projects/importer-source-readiness-copilot/tests/test_operator_screenshots.py",
    "product_projects/importer-source-readiness-copilot/tests/test_source_packet_workflow.py",
    "product_projects/importer-source-readiness-copilot/tests/test_customer_store.py",
    "product_projects/importer-source-readiness-copilot/tests/test_product_runtime.py",
    "product_projects/importer-source-readiness-copilot/tests/test_policy_intelligence.py",
    "product_projects/importer-source-readiness-copilot/tests/test_completion_platform.py",
    "product_projects/importer-source-readiness-copilot/tests/test_business_logic.py",
    "product_projects/importer-source-readiness-copilot/tests/test_external_package_audit.py",
    "product_projects/importer-source-readiness-copilot/tests/test_external_review_workflow.py",
    "product_projects/importer-source-readiness-copilot/tests/test_final_go_live.py",
    "product_projects/importer-source-readiness-copilot/tests/test_external_validation_research.py",
    "product_projects/importer-source-readiness-copilot/system_review_graph/readiness_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/external_gate_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/continuation_plan.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/vc_pitch_readiness_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/board_go_live_readiness_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/operator_workflow_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/operator_dashboard.html",
    "product_projects/importer-source-readiness-copilot/system_review_graph/operator_screenshot_manifest.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/operator_screenshots/operator-dashboard.png",
    "product_projects/importer-source-readiness-copilot/system_review_graph/customer_readiness_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/customer_readiness_report.md",
    "product_projects/importer-source-readiness-copilot/system_review_graph/customer_source_packets.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/evidence_ledger.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/customer_ai_review_runs.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/customer_workflow.sqlite",
    "product_projects/importer-source-readiness-copilot/system_review_graph/product_runtime_state.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/auth_rbac_matrix.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/claims_gate_matrix.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/review_requests.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/human_review_findings.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/report_exports.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/audit_events.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/deletion_requests.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/deployment_readiness_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/private_beta_readiness_checklist.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/ai_data_policy.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/model_endpoints.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/ai_model_router.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/redaction_pipeline.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/manual_no_ai_workflow.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/requirements_traceability_matrix.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/public_trade_readiness_manifest.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/exporter_mode_requirements.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/public_report_types.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/public_upload_policy.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/intelligence_hub_policy_monitor.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/policy_source_snapshots.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/policy_change_impact_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/policy_intelligence.sqlite",
    "product_projects/importer-source-readiness-copilot/system_review_graph/completion_platform_manifest.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/country_coverage_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/opportunity_scanner_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/business_logic_phase_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/transport_readiness_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/billing_credit_controls.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/agent_api_manifest.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/traffic_pages_manifest.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/research_execution_plan.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/team_workspace_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/expert_network_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/billing_usage_ledger.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/agent_api_gateway_contract.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/launch_operations_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/all_stage_readiness_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/product_operations_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/product_operations_log.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/final_go_live_decision_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/current_external_gate_research.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/external_validation_requirements_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/external_validation_evidence_requirements.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/go_live_input_templates.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/go_live_input_readiness_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/reviewer_wave_execution_plan.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/private_beta_smoke_test_plan.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/external_review_findings_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/external_review_blocker_ledger.jsonl",
    "product_projects/importer-source-readiness-copilot/system_review_graph/ai_assisted_external_review_plan.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/ai_assisted_external_review_findings_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/research_execution_runs.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/expert_review_work_orders.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/team_workspace_activity.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/launch_operations_events.json",
    "product_projects/importer-source-readiness-copilot/START_HERE.md",
    "product_projects/importer-source-readiness-copilot/WHAT_WE_ARE_BUILDING.md",
    "product_projects/importer-source-readiness-copilot/CURRENT_SLICE_VS_TARGET_PRODUCT.md",
    "product_projects/importer-source-readiness-copilot/FINAL_GO_LIVE_HANDOFF.md",
    "product_projects/importer-source-readiness-copilot/system_review_graph/generated_reports/data_intake_packet-frozen-tuna-canada-001.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/generated_reports/missing_evidence_packet-frozen-tuna-canada-001.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/generated_reports/starter_checklist_packet-frozen-tuna-canada-001.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/generated_reports/chatgpt_safe_summary_packet-frozen-tuna-canada-001.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/generated_reports/broker_packet_packet-frozen-tuna-canada-001.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/generated_reports/business_decision_packet-frozen-tuna-canada-001.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/source_refresh_runs.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/source_refresh_report_packet-frozen-tuna-canada-001.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/expert_review_packet_packet-frozen-tuna-canada-001.md",
    "product_projects/importer-source-readiness-copilot/output/pdf/external_validation_requirements.pdf",
    "product_projects/importer-source-readiness-copilot/output/pdf/external_validation_reviewer_brief.pdf",
    "product_projects/importer-source-readiness-copilot/output/pdf/go_live_input_requests.pdf",
    "product_projects/importer-source-readiness-copilot/system_review_graph/blockers.jsonl",
    "product_projects/importer-source-readiness-copilot/investor/vc_pitch_deck.md",
    "product_projects/importer-source-readiness-copilot/investor/one_pager.md",
    "product_projects/importer-source-readiness-copilot/investor/demo_script.md",
    "product_projects/importer-source-readiness-copilot/investor/diligence_room_index.md",
    "product_projects/importer-source-readiness-copilot/board/board_go_live_brief.md",
    "product_projects/importer-source-readiness-copilot/board/expert_review_packet.md",
    "product_projects/importer-source-readiness-copilot/board/launch_control_checklist.md",
    "product_projects/importer-source-readiness-copilot/board/financial_operating_model.md",
    "product_projects/importer-source-readiness-copilot/migrations/0001_product_runtime.sql",
    "product_projects/importer-source-readiness-copilot/Dockerfile",
    "product_projects/importer-source-readiness-copilot/compose.yaml",
    "product_projects/importer-source-readiness-copilot/.env.example",
    "product_projects/importer-source-readiness-copilot/docs/SECURITY_PRIVACY.md",
    "product_projects/importer-source-readiness-copilot/docs/DEPLOYMENT.md",
    "product_projects/importer-source-readiness-copilot/handoffs/product_completion_handoff.md",
    "product_projects/importer-source-readiness-copilot/external_review_findings/README.md",
    "product_projects/importer-source-readiness-copilot/external_review_findings/UX_PRODUCT_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/external_review_findings/SECURITY_PUBLIC_UPLOAD_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/external_review_findings/PRIVACY_LEGAL_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/external_review_findings/AI_SAFETY_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/external_review_findings/TRADE_BOUNDARY_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/external_review_findings/FREIGHT_LOGISTICS_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/external_review_findings/REPORT_LANGUAGE_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/external_review_findings/DEVOPS_PRODUCTION_READINESS_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/external_review_findings/BILLING_PAYMENT_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/external_review_findings/EXTERNAL_REVIEW_SUMMARY.json",
    "product_projects/importer-source-readiness-copilot/reviewer_packets/README.md",
    "product_projects/importer-source-readiness-copilot/reviewer_packets/WAVE_1_UX_PRODUCT_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/reviewer_packets/WAVE_1_SECURITY_PUBLIC_UPLOAD_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/reviewer_packets/WAVE_1_PRIVACY_LEGAL_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/reviewer_packets/WAVE_1_AI_SAFETY_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/reviewer_packets/WAVE_1_DEVOPS_PRODUCTION_READINESS_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/reviewer_packets/WAVE_2_TRADE_BOUNDARY_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/reviewer_packets/WAVE_2_FREIGHT_LOGISTICS_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/reviewer_packets/WAVE_2_REPORT_LANGUAGE_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/reviewer_packets/WAVE_3_BILLING_PAYMENT_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/README.md",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/AI_ASSISTED_REVIEW_SUMMARY.md",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/WEB_RESEARCH_SOURCE_LOG.md",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/simulated_findings/.gitkeep",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/simulated_findings/WAVE_1_UX_PRODUCT_REVIEW.json",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/simulated_findings/WAVE_1_SECURITY_PUBLIC_UPLOAD_REVIEW.json",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/simulated_findings/WAVE_1_PRIVACY_LEGAL_REVIEW.json",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/simulated_findings/WAVE_1_AI_SAFETY_REVIEW.json",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/simulated_findings/WAVE_1_DEVOPS_PRODUCTION_READINESS_REVIEW.json",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/role_prompts/WAVE_1_UX_PRODUCT_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/role_prompts/WAVE_1_SECURITY_PUBLIC_UPLOAD_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/role_prompts/WAVE_1_PRIVACY_LEGAL_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/role_prompts/WAVE_1_AI_SAFETY_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/role_prompts/WAVE_1_DEVOPS_PRODUCTION_READINESS_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/role_prompts/WAVE_2_TRADE_BOUNDARY_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/role_prompts/WAVE_2_FREIGHT_LOGISTICS_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/role_prompts/WAVE_2_REPORT_LANGUAGE_REVIEW.md",
    "product_projects/importer-source-readiness-copilot/ai_assisted_review/role_prompts/WAVE_3_BILLING_PAYMENT_REVIEW.md",
    "templates/STARTUP_BRIEF.md",
    "templates/STARTUP_LIFECYCLE.md",
    "templates/INSTRUCTION_CONTRACT.md",
    "templates/COMPLEXITY_CLASSIFICATION.md",
    "templates/AGENT_TASK_SPEC.md",
    "templates/DELIVERY_ESTIMATE.md",
    "templates/ARCHITECTURE_OVERVIEW.md",
    "templates/WORK_PACKAGE.md",
    "templates/ESTIMATE_VS_ACTUAL.md",
    "templates/COMPLEX_PRODUCT_SPEC.md",
    "templates/HARDWARE_RESEARCH_RECORD.md",
    "templates/TOOL_DECISION_RECORD.md",
    "templates/PROCUREMENT_AND_LAB_PLAN.md",
    "templates/MODULE_CONTRACT.md",
    "templates/HANDOFF.md",
    "templates/PROOF_GATE.md",
    "templates/CURRENT_STATE_PROMPT.md",
    "templates/STATE_RECONSTRUCTION_REPORT.md",
    "templates/RESEARCH_RECORD.md",
    "templates/PRODUCT_AUTOMATION_RUNBOOK.md",
    "templates/EXTERNAL_HARNESS_ADOPTION.md",
    "templates/NEXT_AGENT_PROMPT.md",
    "templates/WORKFLOW_AUTOMATION.md",
    "templates/AGENTIC_EXECUTION_PLAN.md",
    ".agents/skills/ai-native-delivery/SKILL.md",
    "scripts/no_scaffold_audit.py",
    "scripts/self_test_flow.py",
    "scripts/product_project_check.py",
    "scripts/product_readiness_scorecard.py",
    "scripts/system_review_graph.py",
    "scripts/workflow_manifest_check.py",
    "scripts/agentic_workflow_orchestrator.py",
    "system_review_graph/prompt_to_product_packet.json",
    "system_review_graph/internal_repo_intake_packet.json",
    "system_review_graph/research_data_plan.json",
    "system_review_graph/development_strategy_plan.json",
    "system_review_graph/external_harness_integration_packet.json",
    "system_review_graph/slash_command_specs.json",
    "system_review_graph/no_scaffold_audit_report.json",
    "system_review_graph/no_scaffold_audit_report.md",
    "system_review_graph/product_readiness_scorecard.json",
    "system_review_graph/system_review_graph_summary.json",
    "system_review_graph/code_graph.md",
    "system_review_graph/data_graph.md",
    "system_review_graph/flow_graph.md",
    "system_review_graph/proof_graph.md",
    "system_review_graph/task_graph.md",
    "system_review_graph/resource_graph.md",
    "system_review_graph/lane_packet_workflow-coordinator.json",
    "system_review_graph/automation_runtime_report.json",
    "system_review_graph/scheduler_plan.json",
    "system_review_graph/eval_report.json",
    "system_review_graph/blocker_ledger_report.json",
    "handoffs/ci_fix_workflow-manifest-ci.json",
]

REQUIRED_GLOBS = [
    "external_review_packages/importer-source-readiness-external-review-v2-*.zip",
    "external_review_packages/importer-source-readiness-external-review-v2-*.zip.sha256",
    "external_review_packages/importer-source-readiness-external-review-v2-*/REVIEW_PACKAGE_MANIFEST.json",
    "external_review_packages/importer-source-readiness-external-review-v3-*.zip",
    "external_review_packages/importer-source-readiness-external-review-v3-*.zip.sha256",
    "external_review_packages/importer-source-readiness-external-review-v3-*/REVIEW_PACKAGE_MANIFEST.json",
    "external_review_packages/importer-source-readiness-technical-source-review-*.zip",
    "external_review_packages/importer-source-readiness-technical-source-review-*.zip.sha256",
    "external_review_packages/importer-source-readiness-technical-source-review-*/REVIEW_PACKAGE_MANIFEST.json",
    "external_review_packages/importer-source-readiness-technical-source-review-v3-*.zip",
    "external_review_packages/importer-source-readiness-technical-source-review-v3-*.zip.sha256",
    "external_review_packages/importer-source-readiness-technical-source-review-v3-*/REVIEW_PACKAGE_MANIFEST.json",
]


def main() -> int:
    missing = [path for path in REQUIRED if not (ROOT / path).exists()]
    missing_patterns = [pattern for pattern in REQUIRED_GLOBS if not list(ROOT.glob(pattern))]
    if missing:
        print("AI Dev OS check: FAIL")
        for path in missing:
            print(f"missing: {path}")
        return 1
    if missing_patterns:
        print("AI Dev OS check: FAIL")
        for pattern in missing_patterns:
            print(f"missing_pattern: {pattern}")
        return 1
    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp = Path(tmp_dir)
        audit_result = subprocess.run(
            [
                "python3",
                "scripts/no_scaffold_audit.py",
                "--check",
                "--out",
                str(tmp / "no_scaffold_audit_report.json"),
                "--md-out",
                str(tmp / "no_scaffold_audit_report.md"),
            ],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        if audit_result.returncode != 0:
            print("AI Dev OS check: FAIL")
            print(audit_result.stdout)
            print(audit_result.stderr)
            return audit_result.returncode
        scorecard_result = subprocess.run(
            [
                "python3",
                "scripts/product_readiness_scorecard.py",
                "--out",
                str(tmp / "product_readiness_scorecard.json"),
            ],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        if scorecard_result.returncode != 0:
            print("AI Dev OS check: FAIL")
            print(scorecard_result.stdout)
            print(scorecard_result.stderr)
            return scorecard_result.returncode
    print("AI Dev OS check: PASS")
    print(f"required_files={len(REQUIRED)}")
    print(f"required_globs={len(REQUIRED_GLOBS)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
