"""Validate the AI Development OS repository structure."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

REQUIRED = [
    "README.md",
    "AGENTS.md",
    "CONTRIBUTING.md",
    "CONTRIBUTOR_TERMS.md",
    "DCO.txt",
    "GOVERNANCE.md",
    "LICENSE",
    "NOTICE.md",
    "DISCLAIMER.md",
    "ROADMAP.md",
    "SECURITY.md",
    "TRADEMARKS.md",
    "docs/LICENSING.md",
    "docs/COMMERCIAL_AND_ASSOCIATION.md",
    "docs/INSTRUCTION_NORMALIZATION.md",
    "docs/COMPLEXITY_ROUTER.md",
    "docs/AGENTIC_COMPANY_MODEL.md",
    "docs/DELIVERY_ESTIMATION.md",
    "docs/AI_NATIVE_DELIVERY.md",
    "docs/PRODUCT_AUTOMATION_GUIDE.md",
    "docs/AGENTIC_WORKFLOW_INTEGRATION.md",
    "docs/STARTUP_CONTINUATION_RULE.md",
    "docs/SYSTEM_REVIEW_GRAPH.md",
    "docs/STATE_RECONSTRUCTION.md",
    "docs/AI_LIFECYCLE.md",
    "docs/BIDIRECTIONAL_PRODUCT_LOOP.md",
    "docs/PROMPT_TO_PRODUCT.md",
    "docs/COMPLEX_PRODUCT_PLAYBOOK.md",
    "docs/TOOL_BREEDING_GROUND.md",
    "docs/STRATEGY_RESEARCH_PLAYBOOK.md",
    "docs/TOOLCHAIN.md",
    "docs/OPEN_SOURCE_RESOURCES.md",
    "docs/RESEARCH_INTAKE.md",
    "docs/CODEX_USAGE.md",
    "manifests/tool_registry.yaml",
    "manifests/agent_lanes.yaml",
    "manifests/agentic_workflow_manifest.json",
    "manifests/agentic_execution_manifest.json",
    "manifests/internal_repo_registry.json",
    "manifests/research_data_router.json",
    "manifests/development_strategy_router.json",
    ".github/pull_request_template.md",
    ".github/ISSUE_TEMPLATE/bug_report.md",
    ".github/ISSUE_TEMPLATE/process_gap.md",
    "examples/README.md",
    "examples/calculator_app_prompt.txt",
    "examples/calculator_app_expected/COMPLEXITY_CLASSIFICATION.md",
    "examples/hardware_os_startup_prompt.txt",
    "examples/hardware_os_startup_expected/COMPLEXITY_CLASSIFICATION.md",
    "examples/hardware_os_startup_expected/INSTRUCTION_CONTRACT.md",
    "examples/hardware_os_startup_expected/ARCHITECTURE_OVERVIEW.md",
    "examples/hardware_os_startup_expected/DELIVERY_ESTIMATE.md",
    "examples/hardware_os_startup_expected/TOOL_DECISION_RECORD.md",
    "product_projects/README.md",
    "product_projects/importer-source-readiness-copilot/README.md",
    "product_projects/importer-source-readiness-copilot/AGENTS.md",
    "product_projects/importer-source-readiness-copilot/docs/PRODUCT_AUTOMATION_RUNBOOK.md",
    "product_projects/importer-source-readiness-copilot/docs/PRODUCT_STATUS.md",
    "product_projects/importer-source-readiness-copilot/docs/OPERATOR_GUIDE.md",
    "product_projects/importer-source-readiness-copilot/data/sample_source_cards.json",
    "product_projects/importer-source-readiness-copilot/data/country_requirements_matrix.json",
    "product_projects/importer-source-readiness-copilot/data/evidence_packets.json",
    "product_projects/importer-source-readiness-copilot/data/official_source_registry.json",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/readiness.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/external_gates.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/continuation.py",
    "product_projects/importer-source-readiness-copilot/src/importer_source_readiness/operator_report.py",
    "product_projects/importer-source-readiness-copilot/scripts/run_readiness.py",
    "product_projects/importer-source-readiness-copilot/scripts/run_external_gates.py",
    "product_projects/importer-source-readiness-copilot/scripts/export_operator_dashboard.py",
    "product_projects/importer-source-readiness-copilot/scripts/plan_continuation.py",
    "product_projects/importer-source-readiness-copilot/scripts/check_product.py",
    "product_projects/importer-source-readiness-copilot/tests/test_readiness.py",
    "product_projects/importer-source-readiness-copilot/tests/test_external_gates.py",
    "product_projects/importer-source-readiness-copilot/tests/test_continuation.py",
    "product_projects/importer-source-readiness-copilot/system_review_graph/readiness_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/external_gate_report.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/continuation_plan.json",
    "product_projects/importer-source-readiness-copilot/system_review_graph/operator_dashboard.html",
    "product_projects/importer-source-readiness-copilot/system_review_graph/blockers.jsonl",
    "product_projects/importer-source-readiness-copilot/handoffs/product_completion_handoff.md",
    "templates/STARTUP_BRIEF.md",
    "templates/INSTRUCTION_CONTRACT.md",
    "templates/COMPLEXITY_CLASSIFICATION.md",
    "templates/AGENT_TASK_SPEC.md",
    "templates/DELIVERY_ESTIMATE.md",
    "templates/ARCHITECTURE_OVERVIEW.md",
    "templates/WORK_PACKAGE.md",
    "templates/ESTIMATE_VS_ACTUAL.md",
    "templates/COMPLEX_PRODUCT_SPEC.md",
    "templates/HARDWARE_RESEARCH_RECORD.md",
    "templates/TOOL_DECISION_RECORD.md",
    "templates/PROCUREMENT_AND_LAB_PLAN.md",
    "templates/MODULE_CONTRACT.md",
    "templates/HANDOFF.md",
    "templates/PROOF_GATE.md",
    "templates/CURRENT_STATE_PROMPT.md",
    "templates/STATE_RECONSTRUCTION_REPORT.md",
    "templates/RESEARCH_RECORD.md",
    "templates/PRODUCT_AUTOMATION_RUNBOOK.md",
    "templates/NEXT_AGENT_PROMPT.md",
    "templates/WORKFLOW_AUTOMATION.md",
    "templates/AGENTIC_EXECUTION_PLAN.md",
    ".agents/skills/ai-native-delivery/SKILL.md",
    "scripts/self_test_flow.py",
    "scripts/product_project_check.py",
    "scripts/workflow_manifest_check.py",
    "scripts/agentic_workflow_orchestrator.py",
    "system_review_graph/prompt_to_product_packet.json",
    "system_review_graph/internal_repo_intake_packet.json",
    "system_review_graph/research_data_plan.json",
    "system_review_graph/development_strategy_plan.json",
    "system_review_graph/slash_command_specs.json",
    "system_review_graph/lane_packet_workflow-coordinator.json",
    "system_review_graph/automation_runtime_report.json",
    "system_review_graph/scheduler_plan.json",
    "system_review_graph/eval_report.json",
    "system_review_graph/blocker_ledger_report.json",
    "handoffs/ci_fix_workflow-manifest-ci.json",
]


def main() -> int:
    missing = [path for path in REQUIRED if not (ROOT / path).exists()]
    if missing:
        print("AI Dev OS check: FAIL")
        for path in missing:
            print(f"missing: {path}")
        return 1
    print("AI Dev OS check: PASS")
    print(f"required_files={len(REQUIRED)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
